# DATABASE (POSTGRES - DOCKER)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/feedbackdb

quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true


# HTTP
quarkus.http.host=0.0.0.0
quarkus.http.port=8080


# SWAGGER
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger


# REST CLIENTS (AZURE FUNCTIONS)
# Alerta de Urgência
quarkus.rest-client.fn-alerta-api.url=https://fn-alerta-urgencia-tch4.azurewebsites.net
quarkus.rest-client.fn-alerta-api.connect-timeout=5000
quarkus.rest-client.fn-alerta-api.read-timeout=5000

# Relatório Semanal
quarkus.rest-client.fn-relatorio-api.url=https://fn-relatorio-semanal-tch4.azurewebsites.net
quarkus.rest-client.fn-relatorio-api.connect-timeout=5000
quarkus.rest-client.fn-relatorio-api.read-timeout=5000


# SCHEDULER (RELATÓRIO SEMANAL)
# Toda segunda-feira às 11h00
relatorio.cron=0 0 11 ? * MON *